name: Feature Request Form
description: File a feature request or question
title: "[Feature Request]: "
labels: "feature"
body:
  - type: markdown
    attributes:
      value: |
       ### Let Olivia, Provvidenza, and Anthony know if you have any additional questions.
  - type: dropdown
    id: feature-or-question
    attributes:
      label: Feature or Question
      description: Select whether this is a feature request, a question about Hubspot, or other
      options:
        - Feature
        - Question
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Request
      description: Use this space to ask your question or describe your request.
      render: shelll
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is this request related to a problem? 
      description: Use this space to describe the problem you are having.
      render: shelll
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Please briefly describe so the CRM support team can adequately address your need(s)
      render: shelll
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Please briefly describe anything else that would help the CRM support team with your request
      render: shelll
    validations:
      required: true
