name: "New User Request form"
description: "Add a new user to Hubspot"
title: "[New User Request]: "
labels: "new-user"
body:
  - type: markdown
    attributes:
      value: |
       ### Need a new meember to be added to Hubspot? Fill the form below
  - type: input
    id: new-user
    attributes:
      label: What is the new user email address?
      description: Please add the email they will use for outreach in Hubspot
      placeholder: yourname@companyname.com
